"""
Hawk-I PDF Report Generator
Uses reportlab to produce a professional inspection report PDF.
"""
from __future__ import annotations

from collections import Counter
from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# ── Severity constants ─────────────────────────────────────────
SEV_BG   = {"L3": colors.HexColor("#fde8ea"), "L2": colors.HexColor("#fff3e0"), "L1": colors.HexColor("#e8f5e9")}
SEV_FG   = {"L3": colors.HexColor("#c0392b"), "L2": colors.HexColor("#d35400"), "L1": colors.HexColor("#1e8449")}
SEV_LABEL = {"L3": "HIGH", "L2": "MEDIUM", "L1": "LOW"}

NAVY  = colors.HexColor("#1a1a2e")
GREY  = colors.HexColor("#6c757d")
LIGHT = colors.HexColor("#f8f9fa")
LINE  = colors.HexColor("#dee2e6")

PAGE_W, PAGE_H = A4
MARGIN = 2 * cm


# ── Footer drawn on every page ─────────────────────────────────
def _draw_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(GREY)
    canvas.drawString(MARGIN, 1.1 * cm, "Generated by Hawk-I — Aerial Infrastructure Inspector")
    canvas.drawRightString(PAGE_W - MARGIN, 1.1 * cm, f"Page {doc.page}")
    canvas.setStrokeColor(LINE)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 1.5 * cm, PAGE_W - MARGIN, 1.5 * cm)
    canvas.restoreState()


# ── Style helpers ──────────────────────────────────────────────
def _styles():
    base = getSampleStyleSheet()

    def make(name, parent="Normal", **kw):
        return ParagraphStyle(name, parent=base[parent], **kw)

    return {
        "title":    make("ReportTitle",   parent="Normal",
                         fontSize=20, fontName="Helvetica-Bold",
                         textColor=NAVY, spaceAfter=2, alignment=TA_LEFT),
        "subtitle": make("ReportSub",    parent="Normal",
                         fontSize=10, textColor=GREY, spaceAfter=3),
        "section":  make("Section",      parent="Normal",
                         fontSize=12, fontName="Helvetica-Bold",
                         textColor=NAVY, spaceBefore=14, spaceAfter=6),
        "body":     make("Body",         parent="Normal",
                         fontSize=10, leading=14),
        "small":    make("Small",        parent="Normal",
                         fontSize=8,  textColor=GREY, leading=11),
        "report":   make("ReportText",   parent="Normal",
                         fontSize=9,  leading=13, leftIndent=10,
                         textColor=colors.HexColor("#333333")),
        "cell":     make("Cell",         parent="Normal",
                         fontSize=8,  leading=11),
    }


def _summary_table(detections: list, S: dict) -> Table:
    """Build the executive summary key-value table."""
    by_sev = Counter(d.get("severity", "L1") for d in detections)
    areas  = [d["area_cm2"] for d in detections if (d.get("area_cm2") or 0) > 0]
    total_area = sum(areas)
    avg_area   = total_area / len(areas) if areas else 0.0
    class_counts = Counter(d["class_name"] for d in detections)
    most_common  = class_counts.most_common(1)[0][0] if class_counts else "—"

    rows = [
        ["Metric", "Value"],
        ["Total Detections",          str(len(detections))],
        ["Critical  (L3 / HIGH)",     str(by_sev.get("L3", 0))],
        ["Medium    (L2 / MEDIUM)",   str(by_sev.get("L2", 0))],
        ["Low       (L1 / LOW)",      str(by_sev.get("L1", 0))],
        ["Total Defect Area",         f"{total_area:.1f} cm\u00b2"],
        ["Average Defect Area",       f"{avg_area:.1f} cm\u00b2"],
        ["Most Common Defect Type",   most_common],
    ]

    t = Table(rows, colWidths=[9.5 * cm, 7.5 * cm])
    style = TableStyle([
        # Header row
        ("BACKGROUND",   (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR",    (0, 0), (-1, 0), colors.white),
        ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",     (0, 0), (-1, 0), 9),
        # Body
        ("FONTNAME",     (0, 1), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE",     (0, 1), (-1, -1), 9),
        ("GRID",         (0, 0), (-1, -1), 0.4, LINE),
        ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",   (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
        ("LEFTPADDING",  (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        # Alternating rows
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [LIGHT, colors.white]),
        # Highlight critical count cell
        ("BACKGROUND",   (1, 2), (1, 2), SEV_BG["L3"]),
        ("TEXTCOLOR",    (1, 2), (1, 2), SEV_FG["L3"]),
        ("FONTNAME",     (1, 2), (1, 2), "Helvetica-Bold"),
    ])
    t.setStyle(style)
    return t


def _detection_table(detections: list) -> Table:
    """Build the full detection data table."""
    header = ["ID", "Defect Type", "Severity", "Area (cm\u00b2)", "Conf %", "GPS Coordinates", "Timestamp"]

    rows = [header]
    sev_rows = []   # (row_index, severity)

    for det in detections:
        sev  = det.get("severity", "L1")
        area = det.get("area_cm2") or 0
        rows.append([
            str(det.get("id", "—")),
            det["class_name"],
            f"{sev} / {SEV_LABEL.get(sev, sev)}",
            f"{area:.1f}" if area > 0 else "—",
            f"{round(det['confidence'] * 100, 1)}%",
            f"{round(det['lat'], 4)}, {round(det['lon'], 4)}",
            str(det.get("detected_at", ""))[:16],
        ])
        sev_rows.append((len(rows) - 1, sev))

    # Column widths sum to ~17cm (A4 usable width with 2cm margins each side)
    col_w = [1.2*cm, 3.6*cm, 2.6*cm, 2.0*cm, 1.6*cm, 3.5*cm, 2.5*cm]

    t = Table(rows, colWidths=col_w, repeatRows=1)

    ts = TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 8),
        ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",      (0, 1), (-1, -1), 7.5),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [LIGHT, colors.white]),
        ("GRID",          (0, 0), (-1, -1), 0.3, LINE),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING",   (0, 0), (-1, -1), 5),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 5),
        ("ALIGN",         (0, 0), (0, -1), "CENTER"),   # ID
        ("ALIGN",         (3, 0), (4, -1), "CENTER"),   # Area + Conf
    ])

    for row_idx, sev in sev_rows:
        ts.add("BACKGROUND", (2, row_idx), (2, row_idx), SEV_BG.get(sev, colors.white))
        ts.add("TEXTCOLOR",  (2, row_idx), (2, row_idx), SEV_FG.get(sev, colors.black))
        ts.add("FONTNAME",   (2, row_idx), (2, row_idx), "Helvetica-Bold")

    t.setStyle(ts)
    return t


def _critical_details(critical: list, S: dict) -> list:
    """Build the critical defect detail flowables."""
    flowables = []
    flowables.append(Paragraph("Critical Defect Details", S["section"]))
    flowables.append(Paragraph(
        f"The following {len(critical)} L3/HIGH severity detection(s) include "
        "full Gemma-3 LLM inspection reports:",
        S["body"],
    ))
    flowables.append(Spacer(1, 8))

    for det in critical:
        area = det.get("area_cm2") or 0
        area_str = f"{area:.1f} cm\u00b2" if area > 0 else "pending"
        conf_pct = round(det["confidence"] * 100, 1)
        ts = str(det.get("detected_at", ""))[:19]

        # Card header row
        header_row = [[
            Paragraph(f"<b>#{det.get('id', '?')} — {det['class_name']}</b>", S["body"]),
            Paragraph(
                f"GPS: {round(det['lat'], 5)}, {round(det['lon'], 5)} &nbsp;|&nbsp; "
                f"Area: {area_str} &nbsp;|&nbsp; Confidence: {conf_pct}% &nbsp;|&nbsp; {ts}",
                S["small"],
            ),
        ]]
        card_header = Table(header_row, colWidths=[7 * cm, 10 * cm])
        card_header.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), SEV_BG["L3"]),
            ("LEFTPADDING",   (0, 0), (-1, -1), 10),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
            ("TOPPADDING",    (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LINEABOVE",     (0, 0), (-1, 0), 2.5, SEV_FG["L3"]),
            ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ]))

        report_paras = [card_header]
        for line in det["llm_report"].strip().split("\n"):
            if line.strip():
                report_paras.append(Paragraph(line, S["report"]))
            else:
                report_paras.append(Spacer(1, 4))
        report_paras.append(Spacer(1, 14))

        flowables.append(KeepTogether(report_paras[:6]))  # keep header + first ~5 lines together
        flowables.extend(report_paras[6:])

    return flowables


# ── Public API ─────────────────────────────────────────────────
def generate_inspection_pdf(detections: list) -> bytes:
    """
    Generate a professional Hawk-I inspection report PDF.

    Args:
        detections: list of detection dicts from the database.

    Returns:
        Raw PDF bytes.
    """
    if not detections:
        detections = []

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=2.8 * cm,   # room for footer
        title="Hawk-I Inspection Report",
        author="Hawk-I Aerial Infrastructure Inspector",
    )

    S = _styles()
    now = datetime.now().strftime("%Y-%m-%d  %H:%M:%S")
    unique_types = len(set(d["class_name"] for d in detections))
    total = len(detections)

    story = []

    # ── Header ─────────────────────────────────────────────────
    story.append(Paragraph("Hawk-I", S["title"]))
    story.append(Paragraph("Aerial Infrastructure Inspection Report", S["subtitle"]))
    story.append(Spacer(1, 4))
    story.append(HRFlowable(width="100%", thickness=2, color=NAVY, spaceAfter=6))
    story.append(Paragraph(f"Generated: {now}", S["small"]))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        f"Survey completed with <b>{total} detection{'s' if total != 1 else ''}</b> "
        f"across <b>{unique_types} unique defect type{'s' if unique_types != 1 else ''}</b>.",
        S["body"],
    ))
    story.append(Spacer(1, 14))

    # ── Executive Summary ──────────────────────────────────────
    story.append(Paragraph("Executive Summary", S["section"]))
    story.append(_summary_table(detections, S))
    story.append(Spacer(1, 14))

    # ── Detection Table ────────────────────────────────────────
    story.append(Paragraph("All Detections", S["section"]))
    if detections:
        story.append(_detection_table(detections))
    else:
        story.append(Paragraph("No detections recorded.", S["body"]))
    story.append(Spacer(1, 14))

    # ── Critical Defect Details ────────────────────────────────
    critical = [d for d in detections if d.get("severity") == "L3" and d.get("llm_report")]
    if critical:
        story.extend(_critical_details(critical, S))

    doc.build(story, onFirstPage=_draw_footer, onLaterPages=_draw_footer)
    return buffer.getvalue()
